spring.application.name=eCom
spring.datasource.url=jdbc:postgresql://ep-noisy-sea-afsf0vbl-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oBmP9J4Gtsnd
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=mysupersecurejwtkeymysupersecurejwtkey12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.auto-commit=false
spring.servlet.multipart.enabled=true
logging.level.org.springframework.web=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=officiallymercato@gmail.com
spring.mail.password=ehea yxqf piye aavu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true